language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.5-dev" # 3.5 development branch
    - "3.6"
    - "3.6-dev" # 3.6 development branch

# command to install dependencies
install:
    - python -m pip install --upgrade pip
    - sudo apt-get build-dep python-scipy
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install codecov

# command to run tests
script:
    - pytest --cov=./
    - codecov